"""The simulated technician taking a dispatch call.

The outcome (accept / decline / no answer) is decided deterministically by the scenario
policy, so assertions hold. The words spoken are generated by the LLM, so the
conversation is real. Splitting the two keeps the tests reproducible without being wooden.
"""

from __future__ import annotations

from typing import Any

from plumbing.llm import LLM, LLMError
from plumbing.paths import PERSONAS_DIR
from plumbing.world import Technician

_OUTCOME_LABELS = {
    "accepted": "you accept",
    "declined": "you decline",
    "no_answer": "nobody picks up",
}

_OUTCOME_INSTRUCTIONS = {
    "accepted": "You are taking this job. Say roughly how long until you can be there "
    "(about {eta} minutes).",
    "declined": "You are turning this one down. Reason: {reason}. Be polite but clear.",
    "no_answer": "(not used)",
}


class TechnicianSim:
    def __init__(self, llm: LLM, scenario: dict[str, Any]) -> None:
        self.llm = llm
        self.scenario = scenario
        self.template = (PERSONAS_DIR / "technician.md").read_text(encoding="utf-8")

    # ------------------------------------------------------------------
    def __call__(
        self, technician: Technician, job_summary: str, round_number: int = 1
    ) -> dict[str, Any]:
        outcome, reason, eta = self._decide(technician, round_number)

        if outcome == "no_answer":
            return {"outcome": "no_answer", "reason": "No answer", "spoken_reply": ""}

        prompt = (
            self.template.replace("{technician_name}", technician.name)
            .replace("{skills}", ", ".join(technician.skills))
            .replace("{areas}", ", ".join(technician.areas))
            .replace("{status}", technician.status)
            .replace("{round_number}", str(round_number))
            .replace("{job_summary}", job_summary or "(dispatch was vague about it)")
            .replace("{outcome_label}", _OUTCOME_LABELS[outcome])
            .replace(
                "{outcome_instruction}",
                _OUTCOME_INSTRUCTIONS[outcome].format(
                    eta=eta, reason=reason or "still on another job"
                ),
            )
        )
        try:
            spoken = self.llm.chat_text(
                "technician",
                [
                    {"role": "system", "content": prompt},
                    {"role": "user", "content": "(the call connects, you speak)"},
                ],
            )
        except LLMError:
            spoken = (
                "Yeah, got it." if outcome == "accepted" else "Sorry, I can't get there."
            )

        return {
            "outcome": outcome,
            "reason": reason,
            "eta_minutes": eta if outcome == "accepted" else None,
            "spoken_reply": spoken,
        }

    # ------------------------------------------------------------------
    def adjudicate_warranty(
        self, technician: Technician, summary: str, verdict: str, reason: str = ""
    ) -> str:
        """Rule on a warranty claim for work this technician originally did.

        As with dispatch calls, the verdict itself is fixed by the scenario so assertions
        hold; only the wording is generated.
        """
        instruction = (
            "You agree this is your workmanship and it should be covered under warranty. "
            "Say briefly what you think went wrong."
            if verdict == "approve"
            else f"You do not think this is covered by your original work. Reason: "
            f"{reason or 'it is a separate fault, not the work you did'}. Be specific and "
            f"fair — the customer is not being accused of anything."
        )
        prompt = (
            f"You are {technician.name}, a Red Seal plumber. Dispatch has sent you a warranty "
            f"claim on a job you did yourself, and wants your judgement.\n\n"
            f"# The claim\n\n{summary}\n\n"
            f"# Your decision\n\n{instruction}\n\n"
            f"Reply as you would to dispatch: plain English, one or two sentences, no JSON, "
            f"no preamble. Just your verdict and why."
        )
        try:
            return self.llm.chat_text(
                "technician",
                [
                    {"role": "system", "content": prompt},
                    {"role": "user", "content": "(you type your reply to dispatch)"},
                ],
            )
        except LLMError:
            return (
                "Yeah, that's my work, we should cover it."
                if verdict == "approve"
                else "That's not the joint I did — separate issue, shouldn't be warranty."
            )

    # ------------------------------------------------------------------
    def report_job_outcome(
        self, technician: Technician, job_summary: str, result: str, reason: str = ""
    ) -> str:
        """Report back after attending: the work is done, or the customer declined.

        Nothing more is asked of them. The agent's only remaining job is to thank the
        customer and close the ticket.
        """
        instruction = (
            "You finished the job. Say briefly what you did."
            if result == "completed"
            else f"You attended, but the customer decided not to go ahead. Reason: "
            f"{reason or 'they did not want to pay for the repair'}. Say so plainly, "
            f"without editorialising about the customer."
        )
        prompt = (
            f"You are {technician.name}, a Red Seal plumber, reporting back to dispatch "
            f"after attending a job.\n\n# The job\n\n{job_summary}\n\n"
            f"# What happened\n\n{instruction}\n\n"
            f"Reply as you would to dispatch: plain English, one or two sentences, no JSON, "
            f"no preamble."
        )
        try:
            return self.llm.chat_text(
                "technician",
                [
                    {"role": "system", "content": prompt},
                    {"role": "user", "content": "(you message dispatch)"},
                ],
            )
        except LLMError:
            return (
                "All done, cleaned up and away."
                if result == "completed"
                else "Attended, but they decided against the repair."
            )

    # ------------------------------------------------------------------
    def _decide(self, technician: Technician, round_number: int) -> tuple[str, str, int]:
        """Parse the policy: accept / decline / no_answer / accept_after_round:N."""
        policy = (technician.policy or "accept").strip()
        eta = int(self.scenario.get("world", {}).get("technician_eta_minutes", 40))
        reason = technician.decline_reason or "still tied up on another job"

        if policy.startswith("accept_after_round:"):
            threshold = int(policy.split(":", 1)[1])
            if round_number >= threshold:
                return "accepted", "", eta
            return "declined", reason, eta

        if policy in ("decline", "always_decline"):
            return "declined", reason, eta
        if policy in ("no_answer", "never_answer"):
            return "no_answer", "No answer", eta
        return "accepted", "", eta
